# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'ignore warnings'
            additional-check-args: ''
            continue-on-error: false
          - name: 'fail on warning'
            additional-check-args: '--warning-mode=fail -PfailOnWarning'
            continue-on-error: true

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.continue-on-error }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew --info --stacktrace functionalTest --tests ScalaSingleModuleTest ${{ matrix.additional-check-args }}

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: test-results/**/*.xml
